version: '3'
services:
  funny_app_rails:
    container_name: funny_app_rails
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./bin/docker_start.sh
    volumes:
      - bundle_path:/bundle
      - .:/app
    ports:
      - "3018:3018"
    environment:
      RAILS_PORT: 3018
    env_file:
      - .env
    links:
      - funny_app_postgres:funny_app_postgres
    depends_on:
      - funny_app_postgres
    tty: true
    stdin_open: true

  funny_app_postgres:
    container_name: funny_app_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password@
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: funny_app_redis
    image: redis:6.2.6
    command: redis-server
    restart: unless-stopped
    volumes:
      - redis:/var/lib/redis/data

volumes:
  bundle_path:
  postgres_data:
  redis:
